# ------------------------------------------------------------------
# LibOpenSteuer - An open-source taxlibrary based on german tax laws
# ------------------------------------------------------------------

# This is the Makefile for the C-source.

# ------------------------------------------------------------------
# Don't make any changes here until you know what you're doing.
# Changes should only be made to the Makefile in the main dir.
# ------------------------------------------------------------------
# Don't compile directly from here. Paths will probably be wrong.
# Use the Makefile in the main directory for compiling/installation.
# ------------------------------------------------------------------

.PHONY : uninstall
uninstall :

.PHONY : clean
clean :
	$(RM) *~
