.TH OPENSTEUER 1 "May 2003" "Version 0.1.0" \
"A taxprogram for german users"
.SH NAME
opensteuer \- An open-source taxprogram based on german tax laws
.SH SYNOPSIS
.B opensteuer
.SH DESCRIPTION
.B OpenSteuer
calculates the tax load based on german tax laws. It is only useful
for people concerned by these laws, which should be german speaking
people normally. For this reason, most of the documentation may be
written in german.
.PP
.B OpenSteuer
is written in Ada95 and uses Gtk+ as its user-interface.
.SH BUGS
All known bugs are documented in the file
.B TODO.
If you find a new bug not mentioned there, report it to
<bugs@opensteuer.de>. Please remind that the bug might already be
fixed in a later version. Before reporting any bugs, try out the
latest available version of \fBOpenSteuer\fR. You will find it at
<http://www.opensteuer.de>.
.SH COPYRIGHT
Copyright (C) 2003 by Hannes Birnbacher, Martin Klaiber and
Sigrid Woersdoerfer.
.SH LICENSE
.B OpenSteuer
is covered by the GNU General Public License (GPL). See the file
.B COPYING
and the source for copying conditions.
.SH AUTHOR
Martin Klaiber <martin@opensteuer.de>.
