.TH LIBOPENSTEUER 3 "December 2003" "Version 0.1.0" \
"A taxlibrary for germany"
.SH NAME
libopensteuer \- A library to calculate german income tax
.SH SYNOPSIS
See libopensteuer-ada(3) how to call the library from Ada programs, or
libopensteuer-c(3) for C programs.
.SH DESCRIPTION
.B LibOpenSteuer
is a library to calculate income tax based on german tax laws.
Currently it has an interface to Ada and C programs. The library
itself is written in Ada95. 
.PP
The library is only useful for people concerned by german tax laws,
which should be german speaking people normally. For this reason, most
of the documentation and all of the other libopensteuer-manpages are
written in german.
.SH BUGS
All known bugs are documented in the file
.B TODO.
If you find a new bug not mentioned there, please report it to
<bugs@opensteuer.de>. Please remind that the bug might already be
fixed in a later version. Before reporting any bugs, try out the
latest available version of this library. You will find it at
\fB<http://www.opensteuer.de>\fR.
.SH COPYRIGHT
Copyright (C) 2003 by Hannes Birnbacher, Martin Klaiber and
Sigrid Woersdoerfer.
.SH LICENSE
.B LibOpenSteuer
is covered by the GNU General Public License (GPL). See the file
.B COPYING
and the source for copying conditions.
.SH AUTHOR
Martin Klaiber <martin@opensteuer.de>.
